In [92]:
from modell import *
from helper import *
from keras.callbacks import ModelCheckpoint
import keras
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import numpy as np
import pandas as pd
import cv2
from sklearn.model_selection import train_test_split
from keras import backend as K 

num_classes = 4
batch_size = 4


# Reads paths of images together with their labels
filename = 'training_combined.csv'
image_list, label_list = read_input_file(filename)
label_list = np.array(label_list)
label_list = np.transpose(label_list)

In [94]:
label_list

array([[0.121875  , 0.17291667, 0.696875  , 0.87916667],
       [0.1140625 , 0.30416667, 0.8859375 , 0.73125   ],
       [0.0203125 , 0.25833333, 0.8765625 , 0.75416667],
       ...,
       [0.        , 0.05416667, 0.7578125 , 1.        ],
       [0.396875  , 0.06458333, 0.5859375 , 0.93541667],
       [0.33125   , 0.21041667, 0.6828125 , 0.94583333]])

In [86]:
image_list = image_list[:98]

In [87]:
label_list = label_list[:98]

In [88]:
train_X, valid_X, train_label, valid_label = train_test_split(image_list, label_list, test_size=0.2, random_state=13)

In [89]:
print(train_X.shape)
print(valid_X.shape)
print(train_label.shape)
print(valid_label.shape)

(78,)
(20,)
(78, 4)
(20, 4)


In [57]:
def generator(features, labels, batch_size):
    num_rows = features.shape[0]
    # Initialize a counter
    
    cv_img = []
    temp=0
    while temp<1:
        counter = 0
#         print('hi')
#         print('hi')
#         print('hi')
#         print('hi')
        # for content, label in zip(features['content'], features['label']):
        for i in features:
            n = cv2.imread("images/" + i)
            # print(i)
            cv_img.append(i)
            
            #X_train[counter%batch_size] = n
            #y_train[counter%batch_size] = labels[counter]
            counter = counter + 1
            if(counter%batch_size == 0):
                train = np.array(cv_img)
#                 cv_img = cv_img.astype('float32')
#                 train = cv_img / 255.
                cv_img = None
                cv_img = []
                print(train, labels[counter-batch_size:counter])
            elif counter==num_rows and counter%batch_size < batch_size:
                train = np.array(cv_img)
#                 cv_img = cv_img.astype('float32')
#                 train = cv_img / 255.
                cv_img = None
                cv_img = []
                print ('HI')
                print(train, labels[counter-batch_size+1:counter])
        temp = temp+1

In [18]:
train_generator = generator(train_X, train_label, batch_size)
val_generator = generator(valid_X, valid_label, batch_size)

train_samples=np.ceil(train_X.shape[0] / batch_size)
val_samples=np.ceil(valid_X.shape[0] / batch_size)

In [58]:
generator(train_X, train_label, batch_size)

['1469052256414DSC_0653.png' '147954714706311.png'] [[0.0578125  0.         1.         1.        ]
 [0.075      0.09791667 0.925      1.        ]]
['1476878834852Untitled1.png' '1470747128351DSC_0256.png'] [[0.1171875  0.11875    0.9875     0.95208333]
 [0.1953125  0.10208333 0.8578125  0.89583333]]
['JPEG_20160526_150511_100091994275.png'
 '1474264827890cobalt-beyond-the-sea-maxi-dress3.png'] [[0.2640625  0.         0.634375   1.        ]
 [0.         0.29166667 1.         0.6875    ]]
['147437487175911471341993644-Roadster-Cream-Coloured-Printed-T-shirt-8851471341993393-4.png'
 'JPEG_20161207_165644_1000961805303.png'] [[0.003125   0.30625    0.996875   0.70625   ]
 [0.321875   0.29791667 0.7        0.75833333]]
['JPEG_20160711_113321_1000235741992.png' '1476881557883Untitled1.png'] [[0.3390625  0.13541667 0.690625   0.96875   ]
 [0.0203125  0.25833333 0.8765625  0.75416667]]
['JPEG_20161117_154532_1000146348308.png'
 'JPEG_20160517_140621_1000651031832.png'] [[0.25       0.26458333 

In [91]:
features = train_X
labels = train_label

num_rows = features.shape[0]

cv_img = []
temp=0

counter = 0

for i in features:
    n = cv2.imread("images/" + i)
    # print(i)
    cv_img.append(i)
    counter = counter + 1
    if(counter%batch_size == 0):
        train = np.array(cv_img)
        cv_img = None
        cv_img = []
        print(train, labels[counter-batch_size:counter])
    elif counter==num_rows:
        train = np.array(cv_img)
        print(train, labels[counter-counter%batch_size:counter])

['JPEG_20161126_144054_1000330319257.png' '1471594607670DSC_0103.png'
 '147771738670920161028_170650.png'
 'JPEG_20160820_112743_1000875312594.png'] [[0.0875     0.29166667 0.821875   0.75      ]
 [0.015625   0.36041667 0.99375    0.65625   ]
 [0.1359375  0.16666667 1.         1.        ]
 [0.403125   0.06666667 0.621875   0.98333333]]
['1473409219651black-around-about-tunic-dress2.png'
 '1472630156514m1livi316_charcoal_l_alt_2.png'
 '1474273419910MS-8502372.png' '1476773560971DSC_8789.png'] [[0.0046875  0.18541667 1.         0.71458333]
 [0.         0.15416667 0.978125   0.83333333]
 [0.046875   0.15       1.         1.        ]
 [0.3140625  0.         0.946875   0.93541667]]
['1467893191516DSC_0010.png' 'JPEG_20160607_161754_100010819310.png'
 '1476878834852Untitled1.png' '1480513991329IMG_0475.png'] [[0.2265625  0.36041667 0.9359375  0.66041667]
 [0.15       0.275      0.890625   0.73958333]
 [0.1171875  0.11875    0.9875     0.95208333]
 [0.0515625  0.21666667 0.78125    0.67291667

In [67]:
labels

array([[0.0578125 , 0.        , 1.        , 1.        ],
       [0.075     , 0.09791667, 0.925     , 1.        ],
       [0.1171875 , 0.11875   , 0.9875    , 0.95208333],
       [0.1953125 , 0.10208333, 0.8578125 , 0.89583333],
       [0.2640625 , 0.        , 0.634375  , 1.        ],
       [0.        , 0.29166667, 1.        , 0.6875    ],
       [0.003125  , 0.30625   , 0.996875  , 0.70625   ],
       [0.321875  , 0.29791667, 0.7       , 0.75833333],
       [0.3390625 , 0.13541667, 0.690625  , 0.96875   ],
       [0.0203125 , 0.25833333, 0.8765625 , 0.75416667],
       [0.25      , 0.26458333, 0.9234375 , 0.74791667],
       [0.121875  , 0.17291667, 0.696875  , 0.87916667],
       [0.1390625 , 0.08125   , 0.7625    , 0.89375   ],
       [0.0203125 , 0.1875    , 0.971875  , 0.77083333],
       [0.        , 0.30416667, 1.        , 0.73333333]])

In [ ]:
        for i in features:
            n = cv2.imread("images/" + i)
            # print(i)
            cv_img.append(i)
            
            #X_train[counter%batch_size] = n
            #y_train[counter%batch_size] = labels[counter]
            counter = counter + 1
            if(counter%batch_size == 0):
                train = np.array(cv_img)
#                 cv_img = cv_img.astype('float32')
#                 train = cv_img / 255.
                cv_img = None
                cv_img = []
                print(train, labels[counter-batch_size:counter])
            elif counter==num_rows and counter%batch_size < batch_size:
                train = np.array(cv_img)
#                 cv_img = cv_img.astype('float32')
#                 train = cv_img / 255.
                cv_img = None
                cv_img = []
                print ('HI')
                print(train, labels[counter-batch_size+1:counter])
        temp = temp+1

In [ ]:







# In[2]:




model = ResnetBuilder.build_resnet_9((3, 480, 640), 4)
model.compile(loss=keras.losses.mse, optimizer=keras.optimizers.Adam(), metrics=['mse', bb_intersection_over_union])
model.fit_generator(train_generator, steps_per_epoch=train_samples, epochs=1, verbose=1, 
                    validation_data=val_generator, validation_steps=val_samples)



In [ ]:
# In[3]:


from keras.models import model_from_json


# In[4]:


model_json = model.to_json()
with open("model_1.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model_1.h5")
print("Saved")


# In[5]:


json_file = open('model_1.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
model = model_from_json(loaded_model_json)
model.load_weights("model_1.h5")
print("Loaded")
model.compile(loss=keras.losses.mse, optimizer=keras.optimizers.Adam(), metrics=['mse', bb_intersection_over_union])


# In[29]:


df1 = pd.read_csv('test.csv')

test = df1['image_name']


# In[ ]:


def generator(features, labels, batch_size):
    num_rows = features.shape[0]
    # Initialize a counter
    counter = 0
    cv_img = []
    while True:
        # for content, label in zip(features['content'], features['label']):
        for i in features:
            n = cv2.imread("images/" + i)
            #print(i)
            cv_img.append(n)
            
            #X_train[counter%batch_size] = n
            #y_train[counter%batch_size] = labels[counter]
            counter = counter + 1
            if(counter%batch_size == 0):
                cv_img = np.array(cv_img)
                cv_img = cv_img.astype('float32')
                train = cv_img / 255.
                cv_img = None
                cv_img = []
                yield train, labels[counter-batch_size:counter]


# In[41]:


def test_generator(features, batch_size):
    num_rows = features.shape[0]
    counter = 0
    cv_img = []
    # Initialize a counter
    while True:
        for i in features:
            n = cv2.imread("images/" + i)
            cv_img.append(n)
            counter = counter + 1
            if (counter%batch_size == 0):
                cv_img = np.array(cv_img)
                cv_img = cv_img.astype('float32')
                test1 = cv_img / 255.
                cv_img = None
                cv_img = []
                yield test1


# In[42]:


test_samples=np.ceil(test.shape[0] / batch_size)

pred = model.predict_generator(test_generator(test, batch_size), steps=test_samples, verbose=1)


# In[44]:


pred.shape


# In[45]:


test.shape


# In[48]:


pred[0]


# In[ ]:


[0.23278953 0.29601428 0.80433834 0.7575191 ]
[0.23278953 0.29601428 0.80433834 0.7575191 ]


# In[49]:


for i in range(len(pred)):
    print(pred[i])


# In[50]:


xf1 = np.floor(640*pred[:,0])
yf1 = np.floor(480*pred[:,1])
xf2 = np.floor(640*pred[:,2])
yf2 = np.floor(480*pred[:,3])


# In[51]:


final_labels = np.transpose(np.vstack((xf1,xf2,yf1,yf2)))


# In[57]:


final_labels_new = final_labels[:-1]
final_labels_new1 = final_labels[1:]


# In[61]:


final_labels_new.shape


# In[60]:


final_labels_new1.shape


# In[64]:


df1['x1'] = pd.DataFrame(final_labels_new1[:,0])
df1['x2'] = pd.DataFrame(final_labels_new1[:,1])
df1['y1'] = pd.DataFrame(final_labels_new1[:,2])
df1['y2'] = pd.DataFrame(final_labels_new1[:,3])

df1.to_csv('test2.csv',index=False)


# In[63]:


df1 = pd.read_csv('test.csv')


# In[ ]:





# In[ ]:


submission = pd.DataFrame({'fname': test.path.tolist(), 'label': labels})
submission.to_csv('submission.csv', index=False)


# In[ ]:





# In[ ]:




